# Background and foreground colors
background = #110e0e
foreground = #e4e0dd

# Standard colors
palette = 0=#110e0e
palette = 1=#d16168
palette = 2=#e0985c
palette = 3=#cf777d
palette = 4=#d06269
palette = 5=#d26a71
palette = 6=#e09967
palette = 7=#e4e0dd

# Bright colors
palette = 8=#7d7472
palette = 9=#edc0c3
palette = 10=#f7e4d4
palette = 11=#efd2d4
palette = 12=#ecc0c3
palette = 13=#efc8cb
palette = 14=#f8e8dd
palette = 15=#f8f7f6
