$color = rgba(17, 14, 14, 1)
$inner_color = rgba(17, 14, 14, 0.66)
$outer_color = rgba(212, 84, 92, 1)
$font_color = rgba(228, 224, 221, 1)
$placeholder_color = rgba(228, 224, 221, 0.7)
$check_color = rgba(224, 153, 103, 1)
