background            #110e0e
foreground            #e4e0dd

# black
color0  #110e0e
color8  #7d7472

# red
color1  #d16168
color9  #edc0c3

# green
color2  #e0985c
color10  #f7e4d4

# yellow
color3  #cf777d
color11  #efd2d4

# blue
color4  #d06269
color12  #ecc0c3

# magenta
color5  #d26a71
color13  #efc8cb

#cyan
color6  #e09967
color14  #f8e8dd

#white
color7  #e4e0dd
color15  #f8f7f6


